### PR TITLE
Fix thread blocks per multiprocessor calculus when registers are the limiting factor

### PR DESCRIPTION
**Pull request by fabiodrg**
Hello! First of all, thanks for the effort in keeping this online calculator up to date! :smile: 

I need to implement an occupancy calculator for another project, which is based on JavaScript, but not for web browsers (so I plan to adapt this one for my needs). I decided to see how you implemented this and compared it to the latest spreadsheet provided by NVIDIA. I noticed **this calculator is missing an architecture parameter: the max number of registers per thread block**. I managed to find an example where your calculator gives the wrong result.

```
Threads per block: 128
Registers per thread: 85
Shared Memory: 0
```

On Compute Capability 5.0, the number of 32-bit registers per multiprocessor (SM) is the same as the maximum registers per thread block. In this case, your calculator works fine! On CC 5.2, the max registers per thread block are half of the registers per SM. For the input above, the calculator is wrong. In fact, it gives the exact same result as for 5.0 because everything in the architecture is the same apart of this register per block limit.

```
CC 5.0
Expected 5 blocks / SM
Got 5 blocks / SM
---
CC 5.2
Expected 4 blocks / SM
Got 5 blocks / SM
```

This PR handles the problem. However, **my approach drops the support for very old Compute Capability 1.x**. The reason for this:
1. It is the only architecture that allocates registers per block instead of per warp. This requires special cases in the code. The 1.x is deprecated/obsolete for a long type. Is it worth keeping support for it?
2. I could not find the values for max registers per thread block. The latest spreadsheets from NVIDIA only provide 2.0 and onwards data. Developer guides only mention 3.x and onwards. Although I admit I didn't spend too much time on this.

In case you still want to suport old CCs, let me know!

### CODE REVIEW

**Comment by fabiodrg** [comment]
I noticed another problem. Starting with Compute Capability 8.0, the CUDA Runtime consumes a fixed amount of shared memory. Therefore, the formula for computing Shared Memory per Block needs to be tweaked. I will use this PR to propose a fix

**Comment by fabiodrg** [comment]
Fixed! So, from my interpretation on the NVIDIA calculator spreadsheet, the amount of shared memory required by the CUDA Runtime might change with the driver version. I added a new object with the number of bytes each CUDA Runtime needs. Then is just checking if Compute Capability is 8.x, and add that amount of bytes to the user input (shared memory bytes per thread block). The UI was updated accordingly. It shows a new input for entering the CUDA runtime version only if CC is 8.x.

image
image

**Comment by fabiodrg** [comment]
Just one more tweak in UI. If the CUDA runtime uses shared memory, it shows an alert. Just to help the user understanding why in the output the Shared Memory per Block is different from the input
image

**Comment by fabiodrg** [comment]
There are two additional constraints regarding Shared Memory
1. Similar to registers, there is a limit per SM and per Thread Block. So first it is necessary to check if SharedMemPerBlock is less than `config.MaxSharedMemPerBlock` (missing field). If it is not, it is an error, and 0 blocks are allocated. If the constraint is met, then the existing calculation is correct, it is something like `floor(totalSharedMemPerMultiprocessor/SharedMemPerBlock)` (Note: I am not using the actual variable/function names as in the code, but I hope you get the idea :smile: )
2. The available shared memory per multiprocessor is configurable. From the CUDA dev guide, the on-chip memory can be used as Shared Memory or L1 cache. By default, it uses all memory per SM, but the user with CUDA runtime calls or at compile time can configure how the memory is split. So the actual available shared memory size should be user input. The possible configurations are pre-determined.

This is not difficult to implement, but this MR is already somewhat long. I will wait for your feedback, and if you agree I will fix these issues in another PR

**Comment by dmikushin** [comment]
Dear @bryant1410 , I've checked that this PR really corrects a lot of problems in occupancy calculation. **Could you please kindly approve it**, so that @fabiodrg could continue with a bit of further fixes?

**Comment by bryant1410** [comment]
@dmikushin @fabiodrg Sorry for the silence.

I don't work full-time for Xmartlabs anymore, though I occasionally try to help with some little things. While I'm currently not working with CUDA directly since a long time ago, I asked a colleague to take a look at this PR. He hasn't answered yet. But I'm gonna go ahead and merge it as there are 2 people that validate this PR now.

**Pull request merged**
